# Generated by Django 2.2.12 on 2021-11-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', '-price']},
        ),
    ]
