# Generated by Django 2.2.12 on 2021-11-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211122_1828'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Vacuums',
        ),
    ]
