# Generated by Django 2.2.12 on 2021-11-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211122_1842'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='price_gt_0',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(price__gt=0), name='Price_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, description__icontains='sony'), name='Sony_check'),
        ),
    ]
