# Generated by Django 2.2.12 on 2021-11-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211122_1858'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='Sony_check',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, description__icontains='dell'), name='Dell_check'),
        ),
    ]
