# Generated by Django 2.2.12 on 2021-11-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211122_1902'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='Dell_check',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, description__icontains='sony'), name='Sony_check'),
        ),
    ]
