# Generated by Django 2.2.12 on 2021-11-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_price_recalculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.TextField(),
        ),
    ]
